name: Prepare Rust environment

runs:
  using: composite
  steps:
    - name: Cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "Q6uyafVpZV"
        cache-on-failure: true

    - uses: taiki-e/install-action@v2
      with:
        tool: nextest

